spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

camunda.bpm.admin-user:
  id: demo
  password: demo

hazelcast:
  enabled: true
  instance-name: camunda-hazelcast-dev
  map:
    name: myMap-dev
    backup-count: 0  # No backup in dev mode for performance
    time-to-live-seconds: 1800  # Shorter TTL in dev
    # GC-optimized memory management
    max-size:
      policy: USED_HEAP_PERCENTAGE
      value: 40  # Lower memory usage in dev
    eviction:
      policy: LRU
      max-size-check-interval-seconds: 30
    # Memory format optimization for GC
    in-memory-format: BINARY
  
  # Session configuration for dev
  session:
    map-name: "spring-session-sessions-dev"
    max-inactive-interval-minutes: 15  # Shorter session in dev
    cookie-name: "CAMUNDA_SESSION_DEV"
    cookie-secure: false  # HTTP allowed in dev
    cookie-http-only: true
  
  # Development Transaction Configuration
  transaction:
    enabled: true
    timeout-seconds: 60  # Longer timeout for debugging
    type: TWO_PHASE
    isolation: READ_COMMITTED
    retry-count: 5  # More retries for dev testing
    enable-xa: false
    deadlock-detection:
      enabled: true
      timeout-seconds: 20  # Longer deadlock timeout for debugging
      retry-backoff-multiplier: 2.0
      max-retry-delay-seconds: 10
    monitoring:
      enabled: true
      log-transaction-details: true  # Verbose logging in dev
      track-performance-metrics: true
  # Network optimization for reduced GC pressure
  network:
    port-auto-increment: true
    port-count: 100
    join:
      multicast:
        enabled: true
      tcp-ip:
        enabled: false
  # Management and monitoring
  management-center:
    enabled: false
  # Advanced memory management
  serialization:
    portable-version: 0
    use-native-byte-order: false
    byte-order: BIG_ENDIAN
    enable-compression: true
    enable-shared-object: true
    allow-unsafe: false

# Actuator endpoints configuration - separate port to avoid security conflicts
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  server:
    port: 9000

# Health check configuration for Kubernetes probes
# Liveness and Readiness probe configuration
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
      show-components: always
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true
  prometheus:
    access: unrestricted

# Logging configuration for debugging
logging:
  level:
    com.example.workflow: DEBUG
    com.hazelcast: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.session: DEBUG